---
- name: Setup server to clone repo, create virtualenv, install requirements, and setup cron jobs
  hosts: nboil
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Set the timezone to CEST (Europe/Stockholm)
      ansible.builtin.timezone:
        name: "Europe/Stockholm"

    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure unzip is installed
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Clone the Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        force: yes

    - name: Ensure Python3 and virtualenv are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-venv
        state: present

    - name: Create a Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv "{{ venv_path }}"
        creates: "{{ venv_path }}/bin/activate"

    - name: Install Python packages from requirements file
      ansible.builtin.pip:
        requirements: "{{ repo_dest }}/requirements.txt"
        virtualenv: "{{ venv_path }}"

    - name: Download Chromedriver
      ansible.builtin.get_url:
        url: "{{ chromedriver_url }}"
        dest: "/tmp/chromedriver.zip"

    - name: Unzip Chromedriver
      ansible.builtin.unarchive:
        src: "/tmp/chromedriver.zip"
        dest: "/tmp/"
        remote_src: yes
        creates: "/tmp/chromedriver"

    - name: Move Chromedriver to destination
      ansible.builtin.command:
        cmd: mv /tmp/chrome-linux64/chrome "{{ chromedriver_dest }}"

    - name: Ensure Chromedriver is executable
      ansible.builtin.file:
        path: "{{ chromedriver_dest }}"
        mode: "0755"
        state: file

    - name: Set up cron job 1
      ansible.builtin.cron:
        name: "Job 1: Run script1.py"
        minute: "{{ cron_job1_minute }}"
        hour: "{{ cron_job1_hour }}"
        job: "{{ cron_job1_command }}"

    - name: Set up cron job 2
      ansible.builtin.cron:
        name: "Job 2: Run script2.py"
        minute: "{{ cron_job2_minute }}"
        hour: "{{ cron_job2_hour }}"
        job: "{{ cron_job2_command }}"
